---
- name: Run roles on target systems
  hosts: fm_dx_webservers
  roles:
    - role: preperation
      tags:
        - preperation
        - always
    - role: xdrd
      tags:
        - xdrd
    - role: fm_dx_webserver
      tags:
        - fm_dx_webserver
    - role: fm_dx_portforward
      tags:
        - fm_dx_portforward
    - role: fm_dx_plugins
      tags:
        - fm_dx_plugins
