---
- name: Restart fm-dx-webserver
  ansible.builtin.systemd:
    name: fm-dx-webserver
    state: restarted
  become: true

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
