---
- name: Ensure /opt/fm-dx-plugins/ directory exists
  ansible.builtin.file:
    path: /opt/fm-dx-plugins/
    state: directory
    mode: "0755"
    owner: fmdx
    group: fmdx
  become: true

- name: Debug the current plugin details
  ansible.builtin.debug:
    msg: "Processing plugin: {{ item.name }} with URL: {{ item.url }} and install status: {{ item.install }}"

- name: Execute tasks if piet exists and is true
  block:
    - name: Clone or update the plugin repo {{ item.name }}
      ansible.builtin.git:
        repo: "{{ item.url }}"
        dest: /opt/fm-dx-plugins/{{ item.shortname }}
        version: main
        update: true
        force: true

    - name: Synchronize plugin {{ item.shortname }} from remote src to remote dest
      ansible.builtin.synchronize:
        src: "/opt/fm-dx-plugins/{{ item.shortname }}/"
        dest: "/opt/fm-dx-webserver/plugins/"
        mode: push
        rsync_opts:
          - "--exclude README.md"
          - "--exclude LICENSE"
          - "--exclude .git/"
      delegate_to: "{{ inventory_hostname }}"
  when: item.install
