---
- name: Install  nodejs, and npm
  ansible.builtin.apt:
    name:
      - nodejs
      - npm
      - ffmpeg
    state: present
    update_cache: true
  become: true

- name: Add the current user to the audio group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: audio
    append: true
  become: true

- name: Create /opt/fm-dx-webserver directory
  ansible.builtin.file:
    path: /opt/fm-dx-webserver
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  become: true

- name: Clone or update the fm-dx-webserver repo from GitHub
  ansible.builtin.git:
    repo: "{{ fm_dx_webserver_repo }}"
    dest: /opt/fm-dx-webserver
    version: "{{ fm_dx_webserver_branch }}"
    update: true
    force: true
  notify: Restart fm-dx-webserver

- name: Install npm dependencies in the fm-dx-webserver-main directory
  community.general.npm:
    path: /opt/fm-dx-webserver/fm-dx-webserver/
    state: present
  notify: Restart fm-dx-webserver

- name: Check if fm-dx-webserver config file exists
  ansible.builtin.stat:
    path: /opt/fm-dx-webserver/config.json
  register: config_file

- name: Get list of audio devices
  parse_audio_devices_linux:
  register: linux_audio_devices
  when: fmdx_audio_device is not defined
  changed_when: false

- name: Set audio device when none is configured
  ansible.builtin.set_fact:
    fmdx_audio_device: "{{ linux_audio_devices.audio_devices[-1].name }}"
  when: fmdx_audio_device is not defined
  changed_when: false

- name: Create fm-dx-webserver config on first install
  ansible.builtin.template:
    src: config.json.j2
    dest: /opt/fm-dx-webserver/config.json
    mode: "0644"
  notify: Restart fm-dx-webserver

- name: Deploy fm-dx-webserver.service from template
  ansible.builtin.template:
    src: fm-dx-webserver.service.j2
    dest: /etc/systemd/system/fm-dx-webserver.service
    mode: "0644"
  become: true
  notify:
    - Restart fm-dx-webserver

- name: Ensure fm-dx-webserver service is started and enabled
  ansible.builtin.systemd:
    name: fm-dx-webserver
    enabled: true
  become: true
  notify: Restart fm-dx-webserver
