---
- name: Ensure IPv4 forwarding is enabled
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "{{ '1' if fm_dx_portforward_enabled else '0' }}"
    sysctl_set: true
    state: present
    reload: true

- name: Persist IPv4 forwarding setting in /etc/ufw/sysctl.conf
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ufw/sysctl.conf
    regexp: ^#?net.ipv4.ip_forward=.*
    line: net.ipv4.ip_forward={{ "1" if fm_dx_portforward_enabled else "0" }}
    state: present

- name: Ensure IPv6 forwarding is enabled
  become: true
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "{{ '1' if fm_dx_portforward_enabled else '0' }}"
    sysctl_set: true
    state: present
    reload: true

- name: Open port fm-dx-webserver using UFW
  community.general.ufw:
    state: enabled
    rule: allow
    port: "80"
    protocol: tcp
  become: true

- name: Add or remove NAT rules in /etc/ufw/before.rules
  become: true
  ansible.builtin.blockinfile:
    path: /etc/ufw/before.rules
    block: |
      *nat
      :PREROUTING ACCEPT [0:0]
      -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port {{ fm_dx_webserver_port }}
      COMMIT
    marker: "# {mark} ANSIBLE MANAGED NAT RULES"
    state: "{{ 'present' if fm_dx_portforward_enabled else 'absent' }}"
  notify: Reload UFW
