---
- name: Add xdrd user with no interactive login and add to dialout group
  ansible.builtin.user:
    name: xdrd
    shell: /usr/sbin/nologin
    groups: dialout
    append: true
    state: present
  become: true

- name: Install xdrd build dependencies
  ansible.builtin.apt:
    name:
      - libssl-dev
      - pkgconf
      - unzip
      - make
      - gcc
      - git
    state: present
    update_cache: true
  become: true

- name: Create /opt/build-xdrd directory
  ansible.builtin.file:
    path: /opt/build-xdrd
    state: directory
    owner: xdrd
    group: xdrd
    mode: "0755"
  become: true

- name: Clone or update the XDRD repo from GitHub
  ansible.builtin.git:
    repo: https://github.com/kkonradpl/xdrd.git
    dest: /opt/build-xdrd/
    version: master
    update: true
    force: true
  register: xdrd_git_checkout
  become: true
  become_user: xdrd

- name: Build xdrd executable
  ansible.builtin.command:
    cmd: make
    chdir: /opt/build-xdrd/
  become_user: xdrd
  become: true
  when: xdrd_git_checkout.changed # noqa: no-handler no-changed-when

- name: Copy xdrd to /usr/bin
  ansible.builtin.copy:
    src: /opt/build-xdrd/xdrd
    dest: /usr/bin/xdrd
    mode: "0755"
    remote_src: true
  become: true
  notify:
    - Restart xdrd service
    - Restart fm-dx-webserver

- name: Deploy xdrd.service from template
  ansible.builtin.template:
    src: xdrd.service.j2
    dest: /etc/systemd/system/xdrd.service
    mode: "0644"
  become: true
  register: xdrd_service
  notify:
    - Restart xdrd service
    - Restart fm-dx-webserver

- name: Ensure xdrd service is started and enabled
  ansible.builtin.systemd:
    name: xdrd
    enabled: true
  become: true
