---
- name: Restart xdrd service
  ansible.builtin.systemd:
    name: xdrd
    state: restarted
  become: true

- name: Reload xdrd systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
